import { Inter } from "next/font/google";
import "../globals.css";
import Header from "./_components/header";
import Footer from "./_components/footer";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();

  const cookie = cookieStore.get("token");

  if (!cookie) {
    redirect("/login");
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen justify-between">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
